- LICENSE
> [DXP-1528] Create LICENSE

- README.md
> [DXP-1512] cloud readme

- terraform/azure/platform/backend.tf
Reverts streamx-dev/streamx-commerce-accelerator#12
> Revert "backend"

- data/web-resources/js/autocomplete-init.js
> [DXP-1479] autocomplete proper rendering

- spec/model/README.md
- spec/model/SxModel.json
Add swatches to attribute options in Commerce Data Model
> [DXP-1577] Add swatches to attribute options in Commerce Data Model

- mesh/mesh-light.yaml
- mesh/mesh.yaml
> Bump blueprints version to 1.0.5

- data/pages/fragments/header.html
- data/web-resources/js/autocomplete-init.js
- data/web-resources/js/main.published.js
> DXP-1627 autocomplete fixed on mobile + initial calls

- README.md
> DXP-1644: Refine README

- spec/model/SxModel.json
> DXP-1568 Fix SxAttribute's required fields list

- .github/workflows/azure-deploy-streamx.yaml
- .github/workflows/azure-undeploy-streamx.yaml
* Added missing Terraform variables in GH actions
> [DXP-1569] Added missing Terraform variables in GH actions

- spec/model/README.md
- spec/model/SxModel.json
Adjust schema in Accelerator to recent changes
> DXP-1568 Adjust schema in Accelerator to recent changes

- spec/model/README.md
- spec/model/SxModel.json
Include description in product variant
> DXP-1568 Include description in product variant

- terraform/README.md
Added info how to troubleshout lost terraform backend state
> [DXP-1727] Troubleshoot lost backend

- terraform/azure/monitoring-storage/main.tf
- terraform/azure/platform/main.tf
- terraform/azure/state-backend/main.tf
* terraform-azure-platform 0.0.4 update
> [DXP-1645] terraform-azure-platform 0.0.4 update

- .github/workflows/azure-deploy-streamx-large.yaml
- .github/workflows/azure-deploy-streamx-medium.yaml
- .github/workflows/azure-deploy-streamx-small.yaml
- .github/workflows/azure-deploy-streamx.yaml
- terraform/README.md
- terraform/azure/platform/main.tf
- terraform/azure/platform/variables.tf
- terraform/scripts/set-repo-secrets.sh
- terraform/scripts/set-repo-variables.sh
> [DXP-1727] Grafana ingress expose

- spec/model/SxModel.json
Add set of types that the schema can validate
> DXP-1568 Add set of types that the schema can validate

- terraform/azure/platform/config/gateway/values.yaml
- terraform/azure/platform/main.tf
- terraform/azure/platform/modules/apisix/main.tf
- terraform/azure/platform/modules/apisix/variables.tf
Get rid of external etcd for Apisix ingress controler
> [DXP-1569] Apisix withtout external etcd

- terraform/scripts/verify_secrets.sh
>  [DXP-1928] Use date syntax based on OS

- .github/workflows/azure-deploy-streamx-large.yaml
- .github/workflows/azure-deploy-streamx-medium.yaml
- .github/workflows/azure-deploy-streamx-small.yaml
- .github/workflows/azure-deploy-streamx.yaml
- mesh/deployment.yaml
- terraform/README.md
- terraform/scripts/set-repo-secrets.sh
Removed the need for blueprint search cert
> [SXPR-127] Blueprint search certificate is not needed

- mesh/mesh.yaml
Use rocksdb in delivery services
> [DXP-2124] Fix loss of EventTime Map state after container restart

- mesh/mesh-light.yaml
- mesh/mesh.yaml
bump version blueprints to 2.0.7
> bump blueprint version to 2.0.7
